/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData confetti = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData push_pin = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData computer = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData education = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData exchange = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData students_cap = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData meeting = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData pencil_case = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData runer_silhouette_running_fast = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData heartbeat = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fireworks = const IconData(0xe80b, fontFamily: _kFontFam);
}
